setup:
  ansible: .prbuilds/setup.playbook.yml
teardown:
  ansible: .prbuilds/cleanup.playbook.yml
checks:
  microdata:
    endpoints:
      - url: http://localhost:3000/
        expected:
          - WebPage
          - LiveBloke
